<?php

/**
 * @file
 * Contains chatbot_customizer.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function chatbot_customizer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.chatbot_customizer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds customization options to the Chatbot module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function chatbot_customizer_theme() {
  return [
    'chatbot_customizer' => [
      'variables' => [
        'chatbot_color' => NULL,
        'chatbot_logo' => NULL,
      ],
    ],
  ];
}
