<?php

function chatbot_theme($existing, $type, $theme, $path) {
  return [
    'chatbot' => [
      'variables' => ['items' => [], 'title' => '']
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function chatbot_page_attachments(array &$attachments) {
  $config = \Drupal::config('chatbot.settings');
  $customizer_config = \Drupal::config('chatbot_customizer.settings');

  $attachments['#attached']['drupalSettings']['chatbot'] = [
    'api_key' => $config->get('api_key'),
    'endpoint' => $config->get('endpoint'),
    'color' => $customizer_config->get('chatbot_color'),
    'enable_speech_to_text' => $customizer_config->get('enable_speech_to_text'),
    'supported_languages' => $customizer_config->get('supported_languages'),
  ];
}

/**
 * Implements hook_preprocess_HOOK() for chatbot templates.
 */
function chatbot_preprocess_chatbot(&$variables) {
  $customizer_config = \Drupal::config('chatbot_customizer.settings');
  $variables['chatbot_color'] = $customizer_config->get('chatbot_color');
  $variables['enable_speech_to_text'] = $customizer_config->get('enable_speech_to_text');
  $variables['supported_languages'] = $customizer_config->get('supported_languages');
}
